{
 "title": "VictoriaMetrics",
 "description": "Overview for single node VictoriaMetrics v1.32.8 or higher",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(vm_app_version, job)"
   },
   {
    "name": "version",
    "query": "label_values(vm_app_version{job=\"$job\"},  version)"
   }
  ]
 },
 "panels": [
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "content": "<div style=\"text-align: center; font-size: 2em\">$version</div>"
  },
  {
   "title": "Flags",
   "type": "table",
   "description": "Run VM with `-help` flag to see all the available flags with description and default values",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "flag{job=\"$job\", value!=\"secret\", value!=\"\"}"
    }
   ]
  },
  {
   "title": "Total datapoints",
   "type": "singlestat",
   "description": "How many datapoints are in storage",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job\", type!=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Index size",
   "type": "singlestat",
   "description": "How many entries inverted index contains. This value is proportional to the number of unique timeseries in storage(cardinality).",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job\", type=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "vm_app_uptime_seconds{job=\"$job\"}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Requests rate",
   "type": "graph",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{job=\"$job\", path!~\"/favicon.ico\"}[$__interval])) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Query duration",
   "type": "graph",
   "description": "The less time it takes is better.\n* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(vm_request_duration_seconds{job=\"$job\", quantile=~\"(0.5|0.99)\"}) by (path, quantile) > 0",
     "legendFormat": "{{quantile}} ({{path}})"
    }
   ]
  },
  {
   "title": "Active time series",
   "type": "graph",
   "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_cache_entries{job=\"$job\", type=\"storage/hour_metric_ids\"}",
     "legendFormat": "Active time series"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "graph",
   "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with -`memory.allowedPercent` flag. Line `max allowed` shows max allowed memory size for cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cache_size_bytes{job=\"$job\"})",
     "legendFormat": "size"
    },
    {
     "expr": "max(vm_allowed_memory_bytes{job=\"$job\"})",
     "legendFormat": "max allowed"
    }
   ]
  },
  {
   "title": "Churn rate",
   "type": "graph",
   "description": "Shows how many of new time-series are created every second.  High churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_new_timeseries_created_total{job=\"$job\"}[5m]))",
     "legendFormat": "churn rate"
    }
   ]
  },
  {
   "title": "Requests error rate",
   "type": "graph",
   "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_http_request_errors_total{job=\"$job\"}[$__interval])) by (path) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "graph",
   "description": "Slow queries according to `search.logSlowQueryDuration` flag, which is `5s` by default.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_slow_queries_total{job=\"$job\"}[5m]))",
     "legendFormat": "slow queries rate"
    }
   ]
  },
  {
   "title": "Concurrent inserts",
   "type": "graph",
   "description": "Shows how many ongoing insertions are taking place.\n* `max` - equal to number of CPU * 2\n* `current` - current number of goroutines busy with inserting rows into storage\n\nWhen `current` hits `max` constantly, it means storage is overloaded and require more CPU.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_concurrent_addrows_capacity{job=\"$job\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(vm_concurrent_addrows_current{job=\"$job\"})",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_tcplistener_conns{job=\"$job\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "TCP connections rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_tcplistener_accepts_total{job=\"$job\"}[$__interval]))",
     "legendFormat": "connections"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Datapoints ingestion rate",
   "type": "graph",
   "description": "How many datapoints are inserted into storage per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=\"$job\"}[$__interval])) by (type) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Pending datapoints",
   "type": "graph",
   "description": "How many datapoints are in RAM queue waiting to be written into storage. The number of pending data points should be in the range from 0 to `2*<ingestion_rate>`, since VictoriaMetrics pushes pending data to persistent storage every second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vm_pending_rows{job=\"$job\", type=\"storage\"}",
     "legendFormat": "pending datapoints"
    },
    {
     "expr": "vm_pending_rows{job=\"$job\", type=\"indexdb\"}",
     "legendFormat": "pending index entries"
    }
   ]
  },
  {
   "title": "Datapoints",
   "type": "graph",
   "description": "How many datapoints are in the storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"$job\", type != \"indexdb\"})",
     "legendFormat": "datapoints"
    }
   ]
  },
  {
   "title": "LSM parts",
   "type": "graph",
   "description": "Data parts of LSM tree.\nHigh number of parts could be an evidence of slow merge performance - check the resource utilization.\n* `indexdb` - inverted index\n* `storage/small` - recently added parts of data ingested into storage(hot data)\n* `storage/big` -  small parts gradually merged into big parts (cold data)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_parts{job=\"$job\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Disk space usage (datapoints)",
   "type": "graph",
   "description": "Shows amount of on-disk space occupied by data points.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=\"$job\", type!=\"indexdb\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Disk space usage (index)",
   "type": "graph",
   "description": "Shows amount of on-disk space occupied by inverted index.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vm_data_size_bytes{job=\"$job\", type=\"indexdb\"}"
    }
   ]
  },
  {
   "title": "Active merges",
   "type": "graph",
   "description": "The number of on-going merges in storage nodes.  It is expected to have high numbers for `storage/small` metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_active_merges{job=\"$job\"}) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Merge speed",
   "type": "graph",
   "description": "The number of rows merged per second by storage nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_rows_merged_total{job=\"$job\"}[5m])) by(type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Rows ignored",
   "type": "graph",
   "description": "Shows how many rows were ignored on insertion due to corrupted or out of retention timestamps.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vm_rows_ignored_total{job=\"$job\"}) by (reason) > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Logging rate",
   "type": "graph",
   "description": "Shows the rate of logging the messages by their level. Unexpected spike in rate is a good reason to check logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vm_log_messages_total{job=\"$job\"}[5m])) by (level) ",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=\"$job\"}) + sum(vm_cache_size_bytes{job=\"$job\"})",
     "legendFormat": "requested from system"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=\"$job\"}) + sum(vm_cache_size_bytes{job=\"$job\"})",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=\"$job\"})",
     "legendFormat": "stack inuse"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[5m])",
     "legendFormat": "Rate 5m"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=\"$job\"})",
     "legendFormat": "gc duration"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"$job\"}[2m]))",
     "legendFormat": "gc duration"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_num_threads{job=\"$job\"})",
     "legendFormat": "threads"
    }
   ]
  }
 ]
}