{
 "title": "Traffic (ClickHouse)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "IP адрес роутера", "query": "192.168.25.1" }
  ]
 },
 "panels": [
  {
   "title": "Поток трафика",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "Date",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toUInt64(toStartOfMinute($dateTimeCol))*1000 as t,\n    sum(Bytes) as sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     toUInt64(toStartOfMinute(TimeReceived))*1000 as t,     sum(Bytes) as sumbytes FROM default.flows_raw WHERE Date BETWEEN toDate(1586833267) AND toDate(1586833467) AND TimeReceived BETWEEN toDateTime(1586833267) AND toDateTime(1586833467) GROUP BY t ORDER BY t",
     "rawSql": "SELECT\n  (cast(extract(epoch from time_flow) as integer)/30)*30 AS \"time\",\n  sum(bytes*8)/30\nFROM flows\nWHERE\n  $__timeFilter(date_inserted)\nGROUP BY \"time\"\nORDER BY \"time\"",
     "round": "0s"
    }
   ]
  },
  {
   "title": "IP адреса источника трафика",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    if(EType = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(SrcAddr), 13, 4))), IPv6NumToString(SrcAddr)) as srcip,\n    sum(Bytes) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY srcip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT     if(EType = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(SrcAddr), 13, 4))), IPv6NumToString(SrcAddr)) as srcip,     sum(Bytes) AS sumbytes FROM default.flows_raw WHERE TimeReceived >= toDateTime(1585445393) GROUP BY srcip ORDER BY sumbytes DESC",
     "rawSql": "SELECT src_ip, count(*), sum(bytes) AS sumBytes FROM flows GROUP BY src_ip",
     "round": "0s"
    }
   ]
  },
  {
   "title": "IP адреса назначения трафика",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 6 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    if(EType = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(DstAddr), 13, 4))), IPv6NumToString(DstAddr)) as dstip,\n    sum(Bytes) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY dstip\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT     if(EType = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(DstAddr), 13, 4))), IPv6NumToString(DstAddr)) as dstip,     sum(Bytes) AS sumbytes FROM default.flows_raw WHERE TimeReceived >= toDateTime(1585445388) GROUP BY dstip ORDER BY sumbytes DESC",
     "rawSql": "SELECT src_ip, count(*), sum(bytes) AS sumBytes FROM flows GROUP BY src_ip",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Порты отправки трафика",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 6 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    SrcPort as port,\n    sum(Bytes) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY port\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT     toUInt64(toStartOfMinute(TimeReceived))*1000 as t,     sum(Bytes) as sumbytes FROM default.flows_raw WHERE Date BETWEEN toDate(1586833267) AND toDate(1586833467) AND TimeReceived BETWEEN toDateTime(1586833267) AND toDateTime(1586833467) GROUP BY t ORDER BY t",
     "rawSql": "SELECT src_ip, count(*), sum(bytes) AS sumBytes FROM flows GROUP BY src_ip",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Порты назначения трафика",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "TimeReceived",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    DstPort as port,\n    sum(Bytes) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY port\nORDER BY sumbytes DESC",
     "rawQuery": "SELECT     toUInt64(toStartOfMinute(TimeReceived))*1000 as t,     sum(Bytes) as sumbytes FROM default.flows_raw WHERE Date >= toDate(1585442721) AND TimeReceived >= toDateTime(1585442721) GROUP BY t ORDER BY t",
     "rawSql": "SELECT src_ip, count(*), sum(bytes) AS sumBytes FROM flows GROUP BY src_ip",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Информация об интерфейсах оборудования $node",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(ifPhysAddress{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr,ifPhysAddress)"
    },
    {
     "expr": "sum(ifSpeed{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr,ifSpeed)"
    },
    {
     "expr": "sum(ifType_info{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr,ifType_info)"
    },
    {
     "expr": "ifMtu{instance=~\"$node\",job=\"snmp\"}"
    },
    {
     "expr": "sum(ifHCInOctets{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr,ifHCInOctets)"
    },
    {
     "expr": "sum(ifHCInMulticastPkts{instance=~\"$node\",job=\"snmp\"} + ifInBroadcastPkts{instance=~\"$node\",job=\"snmp\"} + ifInUcastPkts{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr)"
    },
    {
     "expr": "sum(ifInErrors{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr,ifInErrors)"
    },
    {
     "expr": "sum(ifHCOutOctets{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr,ifHCOutOctets)"
    },
    {
     "expr": "sum(ifHCOutMulticastPkts{instance=~\"$node\",job=\"snmp\"} + ifOutBroadcastPkts{instance=~\"$node\",job=\"snmp\"} + ifOutUcastPkts{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr)"
    },
    {
     "expr": "sum(ifOutErrors{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr,ifOutErrors)"
    },
    {
     "expr": "sum(ifOperStatus{instance=~\"$node\",job=\"snmp\"})by(instance,job,ifDescr,ifOperStatus) == bool 1"
    }
   ]
  }
 ]
}