{
 "title": "Windows Host Overview",
 "description": "Windows host dashboard for telegraf metrics pumped into Prometheus",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(win_system_System_Up_Time{db=\"windows_metrics\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "win_system_System_Up_Time{host=~\"$hostname\"}",
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "win_mem_Available_Bytes{host=~\"$hostname\",db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "win_cpu_Percent_Processor_Time{host=~\"^$hostname\", instance=\"_Total\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Free_Space\") FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" = 'C:' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Drive C: Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - win_disk_Percent_Free_Space{instance=\"C:\",host=~\"$hostname\",db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT 100 - mean(\"Percent_Free_Space\") FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" = 'C:' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Disk_Read_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "C:" }
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "win_cpu_Percent_Processor_Time{host=~\"^$hostname\", instance=\"_Total\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "legendFormat": "% ProcessorTime",
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Priviledged Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Interrupt Time" ], "type": "alias" }
      ],
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Processor Time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "expr": "win_cpu_Percent_Privileged_Time{host=~\"^$hostname\", instance=\"_Total\", db=\"windows_metrics\"}",
     "legendFormat": "% PrivilegedTime"
    },
    {
     "expr": "win_cpu_Percent_User_Time{host=~\"^$hostname\", instance=\"_Total\", db=\"windows_metrics\"}",
     "legendFormat": "% UserTime"
    },
    {
     "expr": "win_cpu_Percent_Interrupt_Time{host=~\"^$hostname\", instance=\"_Total\", db=\"windows_metrics\"}",
     "legendFormat": "% InterruptTime"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "processes",
     "expr": "win_system_Processes{host=~\"$hostname\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Processes",
     "query": "win_system_Processes{instance=\"$hostname\",db=\"windows_metrics\"}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Processor Queue",
     "expr": "win_system_Processor_Queue_Length{host=~\"$hostname\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ProcessorQueue",
     "query": "SELECT mean(\"Processor_Queue_Length\") FROM \"win_system\" WHERE \"host\" =~ /^$hostname$/ AND \"objectname\" = 'System' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "threads",
     "expr": "win_system_Threads{host=~\"$hostname\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Threads",
     "query": "SELECT mean(\"Threads\") FROM \"win_system\" WHERE \"host\" =~ /^$hostname$/ AND \"objectname\" = 'System' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg_over_time(win_mem_Available_Bytes{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Available Bytes",
     "query": "SELECT mean(\"Available_Bytes\") as \"Available Bytes\", mean(\"Pool_Nonpaged_Bytes\") as \"Pool Nonpaged Bytes\", mean(\"Pool_Paged_Bytes\") as \"Pool Paged Bytes\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(win_mem_Pool_Nonpaged_Bytes{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "Pool Nonpaged Bytes"
    },
    {
     "expr": "avg_over_time(win_mem_Pool_Paged_Bytes{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "Pool Paged Bytes"
    }
   ]
  },
  {
   "title": "Memory Usage Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg_over_time(win_mem_Cache_Faults_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Cache Faults persec",
     "query": "SELECT mean(\"Cache_Faults_persec\") as \"Cache Faults persec\", mean(\"Demand_Zero_Faults_persec\") as \"Demand Zero Faults persec\", mean(\"Page_Faults_persec\") as \"Page Faults persec\", mean(\"Pages_persec\") as \"Pages persec\", mean(\"Transition_Faults_persec\") as \"Transition Faults persec\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(0) ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg_over_time(win_mem_Demand_Zero_Faults_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "Demand Zero Faults persec"
    },
    {
     "expr": "avg_over_time(win_mem_Page_Faults_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "Page Faults persec"
    }
   ]
  },
  {
   "title": "System Paging",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg_over_time(win_mem_Pages_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Pages/sec",
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Pages_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pages/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Page_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page_Faults/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Page_Reads_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page_Reads/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Page_Writes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page_Writes/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "expr": "avg_over_time(win_mem_Page_Faults_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "Pages_Faults/sec"
    },
    {
     "expr": "avg_over_time(win_mem_Page_Reads_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "Pages_Reads/sec"
    },
    {
     "expr": "avg_over_time(win_mem_Page_Writes_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "Pages_writes/sec"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "% Processor Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$hostname: $tag_instance",
     "expr": "win_proc_Percent_Processor_Time{host=~\"$hostname\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "query": "SELECT mean(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($__interval), instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Handle Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$hostname: $tag_instance",
     "expr": "win_proc_Handle_Count{host=~\"$hostname\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "query": "SELECT mean(\"Handle_Count\") as \"Handle Count\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), instance fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Private Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$hostname: $tag_instance",
     "expr": "win_proc_Private_Bytes{host=~\"$hostname\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "query": "SELECT mean(\"Private_Bytes\") as \"Private Bytes\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), instance fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Virtual Bytes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$hostname: $tag_instance",
     "expr": "win_proc_Virtual_Bytes{host=~\"$hostname\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "query": "SELECT mean(\"Virtual_Bytes\") as \"Virtual Bytes\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), instance fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$hostname: $tag_instance",
     "expr": "win_proc_Working_Set{host=~\"$hostname\", db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "query": "SELECT mean(\"Working_Set\") as \"Working Set\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), instance fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "avg_over_time(win_system_Context_Switches_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Context Switches persec",
     "query": "SELECT mean(\"Context_Switches_persec\") AS \"Context Switches persec\" FROM \"win_system\" WHERE \"host\" =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "avg_over_time(win_system_System_Calls_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "System Calls/sec",
     "query": "SELECT mean(\"System_Calls_persec\") AS \"System Calls / sec\" FROM \"win_system\" WHERE \"host\" =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Physical Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Physical Disks Latency and Fragmentation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$pdisk $col",
     "expr": "avg_over_time(win_diskio_Avg__Disk_sec_Read{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Disk read latency",
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Avg._Disk_sec/Read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk read latency" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_sec/Write" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk write latency" ], "type": "alias" }
      ],
      [
       { "params": [ "Split_IO_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk  split IO/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "expr": "avg_over_time(win_diskio_Avg__Disk_sec_Write{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "{{instance}} Disk write latency"
    },
    {
     "expr": "avg_over_time(win_diskio_Split_IO_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "{{instance}} Disk Split IO/sec"
    }
   ]
  },
  {
   "title": "Physical Disks Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$pdisk $col",
     "expr": "avg_over_time(win_diskio_Disk_Read_Bytes_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Disk read/sec",
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk read/sec" ], "type": "alias" }
      ],
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk write/sec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "expr": "avg_over_time(win_diskio_Disk_Write_Bytes_persec{host=~\"$hostname\", db=\"windows_metrics\"}[1m])",
     "legendFormat": "{{instance}} Disk write/sec"
    }
   ]
  },
  {
   "title": "Physical Disks Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$pdisk $col",
     "expr": "avg_over_time(win_diskio_Current_Disk_Queue_Length{host=~\"$hostname\",db=\"windows_metrics\"}[30s])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Current Disk Queue Length",
     "measurement": "win_diskio",
     "select": [
      [
       { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current Disk Queue Length" ], "type": "alias" }
      ],
      [
       { "params": [ "Avg._Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Average Disk Queue Length" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "expr": "avg_over_time(win_diskio_Avg__Disk_Queue_Length{host=~\"$hostname\",db=\"windows_metrics\"}[30s])",
     "legendFormat": "{{instance}} Avg Disk Queue Length"
    }
   ]
  },
  { "title": "Logical Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Logical Disk Used %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "expr": "100-win_disk_Percent_Free_Space{host=~\"$hostname\",db=\"windows_metrics\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "win_disk",
     "query": "SELECT (100 - mean(\"Percent_Free_Space\")) as Used FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval), \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Logical Disk Usage Split",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "expr": "avg_over_time(win_disk_Percent_Disk_Read_Time{host=~\"$hostname\",db=\"windows_metrics\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "query": "SELECT mean(\"Percent_Disk_Read_Time\") AS \"% Disk Read Time\", mean(\"Percent_Disk_Write_Time\") AS \"% Disk Write Time\" FROM \"win_disk\" WHERE \"host\" =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logical Disks Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance $col",
     "expr": "avg_over_time(win_disk_Current_Disk_Queue_Length{host=~\"$hostname\",db=\"windows_metrics\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "win_disk",
     "query": "SELECT mean(\"Current_Disk_Queue_Length\") AS \"Current Disk Queue Length\" FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
     "select": [
      [
       { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$hostname: $col",
     "expr": "avg_over_time(win_net_Bytes_Received_persec{host=~\"$hostname\",db=\"windows_metrics\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Bytes Received",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$hostname: $col",
     "expr": "avg_over_time(win_net_Bytes_Sent_persec{host=~\"$hostname\",db=\"windows_metrics\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Bytes Sent",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$hostname: $col",
     "expr": "avg_over_time(win_net_Packets_Received_persec{host=~\"$hostname\",db=\"windows_metrics\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Packets Received",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$hostname: $col",
     "expr": "avg_over_time(win_net_Packets_Sent_persec{host=~\"$hostname\",db=\"windows_metrics\"}[30s])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}} Packets Sent",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}